---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    
    - name: Apply patch operation to an existing kubernetes object
      kubernetes.core.k8s_json_patch:
        host: "{{ api_url }}"
        api_key: "{{ api_token }}"
#        username: "{{ ocp_username }}"
#        password: "{{ ocp_password }}"
        validate_certs: false
        kind: "{{ ocp_object_kind }}"
        namespace: "{{ ocp_namespace }}"
        name: "{{ ocp_object_name }}"
        patch:
#          - op: add
#            path: /metadata/labels/app
#            value: myapp
          - op: replace
            path: "{{ patch_path }}"
            value: "{{ patch_value }}"
